"$schema" = "schemas/schema.json"

[default]
description = "Default permissions for the canvas plugin"
permissions = [
    "allow-show-canvas",
    "allow-hide-canvas",
    "allow-is-available",
    "allow-activate-pen",
    "allow-deactivate-pen",
    "allow-clear",
    "allow-undo",
    "allow-redo",
    "allow-get-strokes",
    "allow-export-image",
    "allow-export-latest-stroke-fragment",
    "allow-register-listener",
    "allow-remove-listener",
]
